package com.linkedin.oneclick.utils;


/**
 * @author sovsankin@linkedin.com
 */
public class OCException extends RuntimeException
{
  public OCException(Throwable cause)
  {
    super(cause);
  }

  public OCException(String message)
  {
    super(message);
  }

  public OCException(String message, Throwable cause)
  {
    super(message, cause);
  }

  /**
   * Robust alternative to incorrect ex.printStackTrace automatically generated by most IDEs.
   *
   * Convert checked exception into unchecked one, for example:
   * <pre>
   *   try {
   *      // declares 3 types of useless exceptions
   *      Object test= Class.forName("Test").newInstance();
   *   } catch(Exception e) {
   *      throw OCException.unchecked(e);
   *   }
   * </pre>
   *
   * Inspired by com.google.common.base.Throwables#propagate
   */
  public static RuntimeException unchecked(Throwable ex)
  {
    if (ex instanceof RuntimeException)
      return (RuntimeException) ex; // no need to wrap
    else
      return new OCException(ex);
  }
}
